### ISSUE TITLE
Scores are kept at 4 points; no update.

### ISSUE THREAD

**Issue by LeeRyanSA** [ADawesomeguy/AwesomeSciBo#37] opened 2022-04-01 03:17 UTC
I have already talked with ADawesomeguy on a social media platform about this issue. It seems as if for every problem solved and points awarded, it is creating a new entry, or a new user. The solution is to reset the score and further delete the duplicated users. I believe this had started happening after a score reset last year in 2021.

**Comment by xlq902** [comment] 2022-04-01 11:09
Hello; I'm not getting this issue, as shown below: 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/64386991/161252097-c69884ff-641d-4762-8c7f-b87ec840985d.png">
Can you send a screenshot of this issue happening? Thanks!

**Comment by ADawesomeguy** [comment] 2022-04-01 14:41
This seems to have been caused by people having a score of 0 when we transferred from storing things in files to a database. This is not a code thing but rather a database thing but I’ve removed all the 0 entries in the DB and it should fix the problem, albeit excessive duplication in some cases. I’ll probably clone and clean up the DB and update it at some point in the near future.

**Comment by ADawesomeguy** [comment] 2022-04-03 18:16
https://github.com/ADawesomeguy/AwesomeSciBo/blob/2f6f807fa169acf18ef145541f1b254ccfa6eb21/src/helpers/db.ts#L11-L16
The problem is that if the user has a score of 0 anywhere in the DB, it'll create a new entry based on the logic here. Instead of checking the numbers, I feel the code should instead check if the user exists in the DB. Adding @TejasOS.

**Comment by ADawesomeguy** [comment] 2022-04-04 18:48
Ok this should theoretically be fully fixed in c63ccd834d3da6040dc52890dd519e05c287c34e.

**Closed** 2022-04-04 18:48 UTC
